/* tslint:disable */
/* eslint-disable */
/**
 * Neuronpedia - Inference Server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: johnny@neuronpedia.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * One prompt's results as prompt_token x feature_index
 * @export
 * @interface ActivationSourcePost200ResponseResultsInner
 */
export interface ActivationSourcePost200ResponseResultsInner {
    /**
     * The prompt, tokenized.
     * @type {Array<string>}
     * @memberof ActivationSourcePost200ResponseResultsInner
     */
    tokens: Array<string>;
    /**
     * The prompt_token x feature_index array
     * @type {Array<Array<number>>}
     * @memberof ActivationSourcePost200ResponseResultsInner
     */
    result: Array<Array<number>>;
}

/**
 * Check if a given object implements the ActivationSourcePost200ResponseResultsInner interface.
 */
export function instanceOfActivationSourcePost200ResponseResultsInner(value: object): value is ActivationSourcePost200ResponseResultsInner {
    if (!('tokens' in value) || value['tokens'] === undefined) return false;
    if (!('result' in value) || value['result'] === undefined) return false;
    return true;
}

export function ActivationSourcePost200ResponseResultsInnerFromJSON(json: any): ActivationSourcePost200ResponseResultsInner {
    return ActivationSourcePost200ResponseResultsInnerFromJSONTyped(json, false);
}

export function ActivationSourcePost200ResponseResultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActivationSourcePost200ResponseResultsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tokens': json['tokens'],
        'result': json['result'],
    };
}

export function ActivationSourcePost200ResponseResultsInnerToJSON(json: any): ActivationSourcePost200ResponseResultsInner {
    return ActivationSourcePost200ResponseResultsInnerToJSONTyped(json, false);
}

export function ActivationSourcePost200ResponseResultsInnerToJSONTyped(value?: ActivationSourcePost200ResponseResultsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tokens': value['tokens'],
        'result': value['result'],
    };
}

